### PR TITLE
Update sandbox to support new spec for concurrent tests.

### PR DESCRIPTION
**Pull request by tuvistavie**
I updated the sandbox to work as we discussed in #41.

I still need to fix a last issue in Hound before I publish a release with the metadata functionality.

### CODE REVIEW

**Comment by keathley** [comment]
Maybe this is a silly question (feel free to tell me so) but if we're changing the setup examples, does it make sense to only include examples for Hound? For that matter does it make sense to have setup examples at all? Why not just provide some information about the `Sandbox` plug and then link to the testing libraries themselves?

**Comment by josevalim** [comment]
Definitely not a silly question. :)

Since we have two tools for now, I am fine with listing both in the README. Just send a PR and we can have both there.

If the situation changes, we can revisit this, but this is a new and important feature, so the more we talk about it, the better.

Does it make sense?

**Comment by tuvistavie** [comment]
There were already examples for Hound so I simply updated them.
I think that if we update the docs we should do this in another PR, but I have no strong opinion about either adding examples for other libraries or removing the examples and leaving only links.

**Comment by josevalim** [comment]
@tuvistavie can you release a new Hound? :)

**Comment by josevalim** [comment]
Please. :)

**Comment by tuvistavie** [comment]
@josevalim Yes, I'll do this tomorrow! It's getting late here :smile:

**Comment by josevalim** [comment]
Beautiful, once you do, let's update the README to mention the version. Have a good night!

**Comment by keathley** [comment]
@josevalim, @tuvistavie Sounds good! I'll submit another PR later today.

Thanks for taking care of these changes. :heart:

**Comment by tuvistavie** [comment]
@josevalim Hound 1.0 just released :tada:

**Comment by josevalim** [comment]
Oh wow, congratulations! @hashnuke, @tuvistavie, and team! 🎉

**Comment by josevalim** [comment]
@keathley we are going to announce the Ecto 2.0 rc tomorrow and I would love to include wallaby in the concurrent testing section. Is it already ready for Ecto 2.0 rc that moved the information to the user agent or not yet? Thank you!

**Comment by keathley** [comment]
@josevalim I just released the latest version with support for user agent metadata so we're good to go!

**Comment by HashNuke** [comment]
@josevalim Thank you very much for all the feedback you've been giving on our code ~! I've been enjoying & learning reading your detailed feedback.

**Comment by josevalim** [comment]
@keathley would you be so kind to send a pull request that adds how to use phoenix.ecto with wallaby to the README? bullet points are enough, i will tidy everything up soon. :)

**Comment by keathley** [comment]
@josevalim Done :)

**Pull request merged**
